### ISSUE TITLE
Issue running compress_classifier.py

### ISSUE THREAD

**Issue by le000043** [IntelLabs/distiller#559]
I have a few issue when running the example
````$ time python3 compress_classifier.py -a alexnet --lr 0.005 -p 50 ../../../data.imagenet -j 44 --epochs 90 --pretrained --compress=../sensitivity-pruning/alexnet.schedule_sensitivity.yaml
Log file for this run: /home/dat/distiller-pytorch-1.5/examples/classifier_compression/logs/2021.05.18-214637/2021.05.18-214637.log

Log file for this run: /home/dat/distiller-pytorch-1.5/examples/classifier_compression/logs/2021.05.18-214637/2021.05.18-214637.log
Traceback (most recent call last):
  File "compress_classifier.py", line 212, in <module>
    main()
  File "compress_classifier.py", line 74, in main
    app = ClassifierCompressorSampleApp(args, script_dir=os.path.dirname(__file__))
  File "compress_classifier.py", line 164, in __init__
    super().__init__(args, script_dir)
  File "/home/dat/distiller-pytorch-1.5/distiller/apputils/image_classifier.py", line 59, in __init__
    self.logdir = _init_logger(self.args, script_dir)
  File "/home/dat/distiller-pytorch-1.5/distiller/apputils/image_classifier.py", line 331, in _init_logger
    apputils.log_execution_env_state(
  File "/home/dat/distiller-pytorch-1.5/distiller/apputils/execution_env.py", line 90, in log_execution_env_state
    logger.debug("OS: %s", lsb_release.get_lsb_information()['DESCRIPTION'])
AttributeError: module 'lsb_release' has no attribute 'get_lsb_information'

**Comment by Nayrouzzz** [comment]
did you find a solution ??
i'm facing the same problem!
